{
 "title": "Heating",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Puffertemperatur (unten/oben) und Ladestand",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"17_pufferladung\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Pufferladung\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"25_puffer-unten\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Puffer unten\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"24_puffer-oben\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Puffer oben\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Betriebscode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"20_betriebscode\")\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Betriebscode\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Programm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"79_programm\")\n|> map(fn: (r) => ({ r with _value: if r._value == \"AUS\" then 0 else if r._value == \"NORMAL\" then 1 else -1 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Betrieb\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kesselfreigabe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"77_kesselfreigabe\")\n|> map(fn: (r) => ({ r with _value: if r._value == true then 1 else 0 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Kesselfreigabe\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Asche leeren in [h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"108_asche-leeren-in\")\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Asche leeren in\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Servicezeit [h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"107_servicezeit\")\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Servicezeit\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Betriebszeit [h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"106_betriebszeit\")\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Betriebszeit\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aussentemperatur [C°]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"23_aussentemperatur\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Aussentemperatur\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vorlauf [C°] HK. 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"37_vorlauf-ist-1\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Vorlauf IST 1\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"38_pumpe-hk-1\")\n|> map(fn: (r) => ({ r with _value: if r._value == true then 1 else 0 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Pumpe HK 1\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"27_warmwasser-0\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Warmwasser 0\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"28_p-warmwasser-0\")\n|> map(fn: (r) => ({ r with _value: if r._value == true then 1 else 0 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Pumpe Warmwasser 0\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kessel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kesseltemperatur [C°]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"3_kesseltemperatur\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Kesseltemperatur\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"26_pumpe-hp0\")\n|> map(fn: (r) => ({ r with _value: if r._value == true then 1 else 0 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Pumpe HP0\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Betrieb",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"78_betrieb\")\n|> map(fn: (r) => ({ r with _value: if r._value == \"0\" then 0 else if r._value == \"AUS\" then 0 else if r._value == \"START\" then 1 else if r._value == \"ZÜNDUNG\" then 2 else if r._value == \"REGELUNG\" then 4 else if r._value == \"HAND\" then 5 else if r._value == \"NACHLAUF\" then 3 else -1 }))\n|> aggregateWindow(every: v.windowPeriod, fn: last)\n|> set(key: \"_field\", value: \"Betrieb\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CO2 Gehalt",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"18_co2-gehalt\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"CO2 Gehalt\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Leistung",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"95_leistung\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Leistung\")\n|> keep(columns:[\"_field\", \"_time\", \"_value\"])\n|> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Brennstoffzähler [m3]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"heating\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._name == \"116_brennstoffzähler\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> set(key: \"_field\", value: \"Brennstoffzähler\")\n|> yield()\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}